name: SonarQube
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  sonarqube:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"
      - name: Begin
        run: dotnet sonarscanner begin /k:"softserve-dotnet" /n:"softserve-dotnet" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.token="$SONAR_TOKEN"
      - name: Build
        run: dotnet build Products.sln
      - name: End
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
